### ISSUE TITLE
kubernetes-cni is of wrong version

### ISSUE THREAD

**Issue by tirnak** [ntsapek/kubernetes-kubeadm#1]
While Ansible runs, i get following error:
```json
TASK [Install kubelet (version 1.9.1-00)] **************************************
fatal: [node1]: FAILED! => {"cache_update_time": 1566833661, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'kubelet=1.9.1-00'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed"]}
```

Can be fixed by installing `kubernetes-cni` while specifiying the exact version:
```yaml
   - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Install kubernetes-cni (version 0.6.0)
      apt:
        name: kubernetes-cni=0.6.0
        state: present

    - name: Install kubelet (version 1.9.1-00)
      apt:
        name: kubelet=1.9.1-00
        state: present
```
